# -*- coding: utf-8 -*-
"""rice leaf app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUHnBwa7YwAQJkNv-8SVJH-QeoBQgCKI
"""

import streamlit as st
import tensorflow as tf
from tensorflow import keras
import numpy as np
from PIL import Image
import json
import pickle

st.set_page_config(page_title="Rice Leaf Disease Classifier", layout="wide")

@st.cache_resource
def load_model():
    model = keras.models.load_model('rice_leaf_disease_model.h5')
    return model

@st.cache_resource
def load_class_names():
    with open('class_names.json', 'r') as f:
        class_names = json.load(f)
    return class_names

model = load_model()
class_names = load_class_names()

st.title("Rice Leaf Disease Classification")
st.write("Upload an image of a rice leaf to classify its disease condition")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

def preprocess_image(image):
    image = image.resize((224, 224))
    image_array = np.array(image)
    image_array = image_array / 255.0
    image_array = np.expand_dims(image_array, axis=0)
    return image_array

if uploaded_file is not None:
    image = Image.open(uploaded_file)

    col1, col2 = st.columns(2)

    with col1:
        st.image(image, caption="Uploaded Image", use_column_width=True)

    with col2:
        with st.spinner("Classifying..."):
            processed_image = preprocess_image(image)
            predictions = model.predict(processed_image)
            predicted_class = class_names[np.argmax(predictions[0])]
            confidence = np.max(predictions[0])

            st.subheader("Prediction Results")
            st.write(f"**Disease:** {predicted_class}")
            st.write(f"**Confidence:** {confidence:.2%}")

            st.subheader("All Probabilities")
            for i, (class_name, prob) in enumerate(zip(class_names, predictions[0])):
                st.write(f"{class_name}: {prob:.2%}")

st.markdown("---")
st.write("Supported diseases: " + ", ".join(class_names))

def test_single_image(image_path, model, class_names):
    img = Image.open(image_path)
    processed_img = preprocess_image(img)

    prediction = model.predict(processed_img)
    predicted_class = class_names[np.argmax(prediction[0])]
    confidence = np.max(prediction[0])

    plt.figure(figsize=(8, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title(f'Predicted: {predicted_class}\nConfidence: {confidence:.2%}')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.barh(class_names, prediction[0])
    plt.title('Class Probabilities')
    plt.xlabel('Probability')

    plt.tight_layout()
    plt.show()

    return predicted_class, confidence

test_image_path = "/path/to/test/image.jpg"
# predicted_class, confidence = test_single_image(test_image_path, model, class_names)

def data_quality_check(dataset_path):
    issues = []
    image_extensions = ['.jpg', '.jpeg', '.png', '.bmp']

    for class_name in os.listdir(dataset_path):
        class_path = os.path.join(dataset_path, class_name)
        if os.path.isdir(class_path):
            images = [f for f in os.listdir(class_path)
                     if any(f.lower().endswith(ext) for ext in image_extensions)]

            if len(images) == 0:
                issues.append(f"No images found in {class_name}")
                continue

            for img_file in images[:5]:
                try:
                    img_path = os.path.join(class_path, img_file)
                    img = Image.open(img_path)
                    img.verify()
                except Exception as e:
                    issues.append(f"Corrupted image: {img_path} - {str(e)}")

    return issues

quality_issues = data_quality_check(dataset_path)
if quality_issues:
    print("Data Quality Issues Found:")
    for issue in quality_issues:
        print(f"- {issue}")
else:
    print("No data quality issues found")