# -*- coding: utf-8 -*-
"""rice leaf app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUHnBwa7YwAQJkNv-8SVJH-QeoBQgCKI
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import json
import os

st.set_page_config(
    page_title="Rice Leaf Disease Classifier",
    layout="wide"
)

@st.cache_resource
def load_tflite_model():
    try:
        interpreter = tf.lite.Interpreter(model_path='rice_leaf_model.tflite')
        interpreter.allocate_tensors()
        return interpreter
    except Exception as e:
        st.error(f"Error loading TensorFlow Lite model: {e}")
        return None

@st.cache_resource
def load_class_names():
    try:
        with open('class_names.json', 'r') as f:
            class_names = json.load(f)
        return class_names
    except Exception as e:
        st.error(f"Error loading class names: {e}")
        return []

def preprocess_image(image):
    image = image.resize((224, 224))
    image_array = np.array(image)

    if len(image_array.shape) == 2:
        image_array = np.stack([image_array] * 3, axis=-1)
    elif image_array.shape[2] == 4:
        image_array = image_array[:, :, :3]

    image_array = image_array / 255.0
    image_array = image_array.astype(np.float32)
    image_array = np.expand_dims(image_array, axis=0)
    return image_array

def predict_with_tflite(interpreter, image):
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    input_data = preprocess_image(image)
    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()

    output_data = interpreter.get_tensor(output_details[0]['index'])
    return output_data

def main():
    st.title("Rice Leaf Disease Classifier")
    st.write("Upload an image of a rice leaf to classify its disease condition")

    with st.spinner("Loading model..."):
        interpreter = load_tflite_model()
        class_names = load_class_names()

    # Check if files exist
    if not os.path.exists('rice_leaf_model.tflite'):
        st.error("Model file 'rice_leaf_model.tflite' not found. Please ensure it's in the same directory.")
        return

    if not os.path.exists('class_names.json'):
        st.error("Class names file 'class_names.json' not found. Please ensure it's in the same directory.")
        return

    if interpreter is None:
        st.error("Failed to load model interpreter.")
        return

    if not class_names:
        st.error("Failed to load class names.")
        return

    st.success("Model loaded successfully!")

    uploaded_file = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Uploaded Image")
            st.image(image, use_column_width=True)

        with col2:
            st.subheader("Prediction Results")
            with st.spinner("Classifying image..."):
                predictions = predict_with_tflite(interpreter, image)
                predicted_class = class_names[np.argmax(predictions[0])]
                confidence = np.max(predictions[0])

            st.success(f"Prediction: {predicted_class}")
            st.info(f"Confidence: {confidence:.2%}")

            st.subheader("All Probabilities")
            for class_name, prob in zip(class_names, predictions[0]):
                st.write(f"{class_name}: {prob:.2%}")
                st.progress(float(prob))

    st.markdown("---")
    st.write("Supported diseases: " + ", ".join(class_names))

if __name__ == "__main__":
    main()