# -*- coding: utf-8 -*-
"""rice leaf app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUHnBwa7YwAQJkNv-8SVJH-QeoBQgCKI
"""

import streamlit as st
import tensorflow as tf
from tensorflow import keras
import numpy as np
from PIL import Image
import json
import gdown
import os

st.set_page_config(
    page_title="Rice Leaf Disease Classifier",
    layout="wide"
)

# Replace these with your actual Google Drive file IDs
MODEL_FILE_ID = "1yfZArGZLrPyW9ROEz1KLNAXe-7DHhGMR/view?usp=sharing"
CLASS_NAMES_FILE_ID = "1ELLvS_ED0G7W2Aznze5MzeOUGTKVLATB/view?usp=sharing"
LABEL_ENCODER_FILE_ID = "1nFip4mNvF4sibc6h8WvNVUcAVx6GwLhJ/view?usp=sharing"

def download_from_drive(file_id, output_path):
    """Download file from Google Drive if it doesn't exist"""
    if not os.path.exists(output_path):
        try:
            url = f"https://drive.google.com/drive/folders/1eAGqF4-tLMICsVGgM5ARJEpL-7l95f_c?usp=sharing"
            gdown.download(url, output_path, quiet=False)
            st.success(f"Downloaded: {output_path}")
        except Exception as e:
            st.error(f"Error downloading {output_path}: {e}")
            return False
    return True

@st.cache_resource
def load_model():
    # Download model file from Google Drive
    if not download_from_drive(MODEL_FILE_ID, 'rice_leaf_disease_model.h5'):
        return None

    try:
        model = keras.models.load_model('rice_leaf_disease_model.h5')
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

@st.cache_resource
def load_class_names():
    # Download class names file from Google Drive
    if not download_from_drive(CLASS_NAMES_FILE_ID, 'class_names.json'):
        return []

    try:
        with open('class_names.json', 'r') as f:
            class_names = json.load(f)
        return class_names
    except Exception as e:
        st.error(f"Error loading class names: {e}")
        return []

def preprocess_image(image):
    """Preprocess the image for model prediction"""
    image = image.resize((224, 224))
    image_array = np.array(image)

    # Convert grayscale to RGB if needed
    if len(image_array.shape) == 2:
        image_array = np.stack([image_array] * 3, axis=-1)
    elif image_array.shape[2] == 4:
        image_array = image_array[:, :, :3]

    image_array = image_array / 255.0
    image_array = np.expand_dims(image_array, axis=0)
    return image_array

# Main app
def main():
    st.title("Rice Leaf Disease Classifier")
    st.write("Upload an image of a rice leaf to classify its disease condition")

    # Load model and class names
    with st.spinner("Loading model from Google Drive..."):
        model = load_model()
        class_names = load_class_names()

    if model is None:
        st.error("Failed to load the model. Please check the Google Drive file IDs.")
        st.info("Make sure you've replaced the FILE_ID placeholders with your actual Google Drive file IDs")
        return

    if not class_names:
        st.error("Failed to load class names.")
        return

    st.success("Model and class names loaded successfully!")

    # File uploader
    uploaded_file = st.file_uploader(
        "Choose an image",
        type=["jpg", "jpeg", "png"],
        help="Upload a clear image of a rice leaf"
    )

    if uploaded_file is not None:
        try:
            image = Image.open(uploaded_file)

            col1, col2 = st.columns(2)

            with col1:
                st.subheader("Uploaded Image")
                st.image(image, use_column_width=True)

            with col2:
                st.subheader("Prediction Results")

                with st.spinner("Classifying image..."):
                    processed_image = preprocess_image(image)
                    predictions = model.predict(processed_image, verbose=0)
                    predicted_class_idx = np.argmax(predictions[0])
                    predicted_class = class_names[predicted_class_idx]
                    confidence = np.max(predictions[0])

                st.success(f"Prediction: {predicted_class}")
                st.info(f"Confidence: {confidence:.2%}")

                st.subheader("All Probabilities")
                for class_name, prob in zip(class_names, predictions[0]):
                    st.write(f"{class_name}: {prob:.2%}")
                    st.progress(float(prob))

        except Exception as e:
            st.error(f"Error processing image: {e}")

    st.markdown("---")
    st.write("Supported diseases: " + ", ".join(class_names))

    # Debug information (optional - can remove later)
    with st.expander("Debug Information"):
        st.write("Files in current directory:", os.listdir('.'))
        st.write("Model file exists:", os.path.exists('rice_leaf_disease_model.h5'))
        st.write("Class names file exists:", os.path.exists('class_names.json'))

if __name__ == "__main__":
    main()