# -*- coding: utf-8 -*-
"""rice leaf app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUHnBwa7YwAQJkNv-8SVJH-QeoBQgCKI
"""

import streamlit as st
import tensorflow as tf
from tensorflow import keras
import numpy as np
from PIL import Image
import json
import gdown
import os

MODEL_FILE_ID = "your_model_file_id_here"
CLASS_NAMES_FILE_ID = "your_class_names_file_id_here"

def download_from_drive(file_id, output_path):
    """Download file from Google Drive"""
    if not os.path.exists(output_path):
        url = f"https://colab.research.google.com/drive/1aqrQjmew-Ki_QMPrIjidwiFtr5TJbh40?usp=sharing"
        gdown.download(url, output_path, quiet=False)

@st.cache_resource
def load_model():

    download_from_drive(MODEL_FILE_ID, 'rice_leaf_disease_model.h5')

    model = keras.models.load_model('rice_leaf_disease_model.h5')
    return model

@st.cache_resource
def load_class_names():

    download_from_drive(CLASS_NAMES_FILE_ID, 'class_names.json')

    with open('class_names.json', 'r') as f:
        class_names = json.load(f)
    return class_names

model = load_model()
class_names = load_class_names()

def preprocess_image(image):
    image = image.resize((224, 224))
    image_array = np.array(image)

    if len(image_array.shape) == 2:
        image_array = np.stack([image_array] * 3, axis=-1)
    elif image_array.shape[2] == 4:
        image_array = image_array[:, :, :3]

    image_array = image_array / 255.0
    image_array = np.expand_dims(image_array, axis=0)
    return image_array

st.title("Rice Leaf Disease Classifier")
st.write("Upload an image of a rice leaf to classify its disease condition")

uploaded_file = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Uploaded Image")
        st.image(image, use_column_width=True)

    with col2:
        st.subheader("Prediction Results")

        with st.spinner("Classifying image..."):
            processed_image = preprocess_image(image)
            predictions = model.predict(processed_image, verbose=0)
            predicted_class = class_names[np.argmax(predictions[0])]
            confidence = np.max(predictions[0])

        st.success(f"Prediction: {predicted_class}")
        st.info(f"Confidence: {confidence:.2%}")

        st.subheader("All Probabilities")
        for class_name, prob in zip(class_names, predictions[0]):
            st.write(f"{class_name}: {prob:.2%}")
            st.progress(float(prob))

st.markdown("---")
st.write("Supported diseases: " + ", ".join(class_names))